### ISSUE TITLE
Failed to prepare git-hosted package for throttle-bounce

### ISSUE THREAD

**Issue by hardik-vala** [Cside/chrome-notion-search#219] opened 2023-06-11 04:24 UTC
I've cloned this repository locally and tried to run `pnpm install`, but I get this error,

```
ENOENT: no such file or directory, copyfile '/workspaces/paper-trail/.pnpm-store/v3/files/c5/5df5bef2e69dcb57fb61d8ff7074fc1b0a66fc61c0d12f61704117ddd56aeb43cd2ee9830dec1619d7dab64812136d0c38d69811dc113f9ff412145d325dcf' -> '/workspaces/paper-trail/node_modules/.pnpm/github.com+Cside+throttle-debounce@a61b6402af9887ced13c4bc95e3e697859d91210_43ikxsp24utdr34hvlxvixh74m/node_modules/_tmp_719_64a229223137451f1fc48462d7cedaf1/_tmp_719_1645d9fb9fbd8439ab5458dd886db29e/dist/esm/debounce.d.ts'
```

Is there some access issues with the repo, https://github.com/Cside/throttle-debounce?

Additional info.:
* `pnpm` version: `8.6.1`
* `node` version: `v20.0.0`

Any help would be much appreciated.

**Comment by Cside** [comment] 2023-06-11 04:50
What is your OS? I could not reproduce it in my environment.

I found [a same Issue](https://github.com/pnpm/pnpm/issues/4997) .
Please try the following method:
- https://github.com/pnpm/pnpm/issues/4997#issuecomment-1225486902
- https://github.com/pnpm/pnpm/issues/4997#issuecomment-1230527581

**Comment by hardik-vala** [comment] 2023-06-11 23:34
I'm on macOS Monterey (12.0.1), but I'm building the source in a devcontainer with the following config,

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/typescript-node
{
	"name": "Node.js & TypeScript",
	"image": "mcr.microsoft.com/devcontainers/typescript-node:0-20",
	"features": {
		"ghcr.io/devcontainers-contrib/features/pnpm:2": {
			"version": "8.6.1"
		}
	}
}
```

**Comment by hardik-vala** [comment] 2023-06-11 23:57
I was able to bypass the issue (I think), by deleting the `pnpm-lock.yaml`.

```
$ pnpm i

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 8.6.1 → 8.6.2.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.6.2   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /workspaces/paper-trail/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Packages: +818
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/typescript/5.1.3: 7.15 MB/7.15 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.62: 14.9 MB/14.9 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.62: 17.2 MB/17.2 MB, done
Progress: resolved 848, reused 0, downloaded 818, added 818, done
node_modules/.pnpm/@swc+core@1.3.62/node_modules/@swc/core: Running postinstall script, done in 262ms
node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running postinstall script, done in 225ms

dependencies:
+ @crxjs/vite-plugin 2.0.0-beta.17
+ @sentry/integrations 7.39.0 (7.54.0 is available)
+ @sentry/react 7.39.0 (7.54.0 is available)
+ @sentry/tracing 7.39.0 (7.54.0 is available)
+ axios 0.27.2 (1.4.0 is available)
+ axios-cache-interceptor 0.10.7 (1.2.0 is available)
+ compare-versions 6.0.0-rc.1
+ extensible-custom-error 0.0.7
+ lodash.escaperegexp 4.1.2
+ lodash.upperfirst 4.3.1
+ react 18.2.0
+ react-dom 18.2.0
+ react-router-dom 6.8.1 (6.12.1 is available)
+ react-string-replace 1.1.0
+ react-tooltip 5.11.1 (5.13.1 is available)
+ use-query-params 2.1.2 (2.2.1 is available)

devDependencies:
+ @testing-library/jest-dom 5.16.5
+ @testing-library/react 14.0.0
+ @testing-library/user-event 14.4.3
+ @tsconfig/strictest 2.0.1
+ @types/chrome 0.0.237
+ @types/lodash.debounce 4.0.7
+ @types/lodash.escaperegexp 4.1.7
+ @types/lodash.upperfirst 4.3.7
+ @types/node 20.2.5 (20.3.0 is available)
+ @types/react 18.0.28 (18.2.11 is available)
+ @types/react-dom 18.0.11 (18.2.4 is available)
+ @types/testing-library__jest-dom 5.14.5 (5.14.6 is available)
+ @typescript-eslint/eslint-plugin 5.59.9
+ @typescript-eslint/parser 5.59.9
+ @typescript-eslint/typescript-estree 5.59.9
+ @vitejs/plugin-react-swc 3.1.0 (3.3.2 is available)
+ autoprefixer 10.4.14
+ caniuse-lite 1.0.30001488 (1.0.30001499 is available)
+ eslint 8.42.0
+ eslint-config-prettier 8.6.0 (8.8.0 is available)
+ eslint-plugin-import 2.27.5
+ eslint-plugin-jest 27.2.1
+ eslint-plugin-react 7.31.11 (7.32.2 is available)
+ eslint-plugin-react-hooks 4.6.0
+ eslint-plugin-testing-library 5.9.1 (5.11.0 is available)
+ jest 29.5.0
+ jsdom 22.1.0
+ lodash.debounce 4.0.8
+ npm-run-all 4.1.5
+ postcss 8.4.21 (8.4.24 is available)
+ postcss-nested 6.0.0 (6.0.1 is available)
+ prettier 2.8.1 (2.8.8 is available)
+ rimraf 5.0.0 (5.0.1 is available)
+ rollup-plugin-visualizer 5.9.0 (5.9.2 is available)
+ stylelint 15.6.2 (15.7.0 is available)
+ stylelint-config-prettier 9.0.5
+ stylelint-config-recess-order 4.0.0 (4.2.0 is available)
+ stylelint-config-recommended 12.0.0
+ stylelint-config-standard 33.0.0
+ stylelint-csstree-validator 2.0.0 (2.1.0 is available)
+ stylelint-declaration-block-no-ignored-properties 2.7.0
+ stylelint-value-no-unknown-custom-properties 4.0.0
+ throttle-debounce 0.0.1
+ ts-array-length 0.1.2
+ typed-css-modules 0.7.2
+ typescript 5.1.3
+ vite 4.0.4 (4.3.9 is available)
+ vitest 0.31.1 (0.32.0 is available)

 WARN  Issues with peer dependencies found
.
├─┬ stylelint-config-prettier 9.0.5
│ └── ✕ unmet peer stylelint@">= 11.x < 15": found 15.6.2
├─┬ stylelint-csstree-validator 2.0.0
│ └── ✕ unmet peer stylelint@">=7.0.0 <15.0.0": found 15.6.2
└─┬ stylelint-value-no-unknown-custom-properties 4.0.0
  └── ✕ unmet peer stylelint@"10 - 14": found 15.6.2

Done in 1m 59.2s
```

**Comment by Cside** [comment] 2023-06-12 00:01
I see. Is there any difference between deleted `pnpm-lock.yaml` and generated `pnpm-lock.yaml` ?

**Comment by hardik-vala** [comment] 2023-06-13 20:02
Yes, but the [diff](https://gist.github.com/hardik-vala/ada9c3003cb00577fda1051253d72598) is quite big.

**Comment by Cside** [comment] 2023-06-14 11:06
I replaced throttle-debounce with [p-debounce](https://github.com/sindresorhus/p-debounce) .
The same problem will probably not recur in the future, so I'll close this issue.
Thanks for your report.

**Closed by Cside** 2023-06-14 11:06 UTC
